"""SoulCore —— 以「自我核心」为最高准则、以身份感知的自适应遗忘为最高决策原则的
个人 Agent 记忆治理内核。

目标不是记住一切，而是：有策略地遗忘，同时记住自己是谁。
"""

from .contract import (
    SPEC_VERSION,
    GovernanceRecord,
    RedLine,
    RetentionPolicy,
    SoulClaim,
    SoulCore,
    content_hash,
    load_soul,
    parse_spec,
    render_soul_md,
    seal_spec,
    validate_spec,
)
from .decay import (
    DecayConfig,
    EvictionCandidate,
    MemoryNode,
    MemoryTier,
    effective_half_life_days,
    eviction_candidates,
    merge_node,
    normalised_strength,
    strength_at,
)
from .errors import ContractViolation, GovernanceError, SoulCoreError, UnauthorizedOverride
from .identity_engine import (
    Decision,
    IdentityConsistencyEngine,
    SoulVerdict,
    require_human_override,
)
from .metrics import (
    AnchoredMemoryAgent,
    CallableAgent,
    DimensionScore,
    EvaluationReport,
    IdentityEvaluator,
    MemoryHygieneReport,
    Probe,
    ScriptedAgent,
    TargetAgent,
    build_probe_suite,
    memory_hygiene,
)
from .scoring import (
    HeuristicScorer,
    LLMScorer,
    ScoreVector,
    ScoringProfile,
    composite_score,
    from_llm_1_10,
    parse_score_response,
)
from .memory import (
    EDGE_INTERACTED,
    EDGE_INVOLVED,
    EDGE_MENTIONED,
    EVENT_PREFIX,
    PERSON_PREFIX,
    Edge,
    Event,
    EventState,
    MemoryHit,
    MemoryLedger,
    MemoryPolicy,
    MemoryReport,
    ObserveOutcome,
    Person,
    PersonState,
    RecallResult,
    name_similarity,
    text_similarity,
)
from .store import (
    ConsolidationReport,
    JsonlPersistence,
    MemoryStore,
    NullPersistence,
    ObservationResult,
)

__version__ = "0.1.0"

__all__ = [
    "SPEC_VERSION",
    "GovernanceRecord",
    "RedLine",
    "RetentionPolicy",
    "SoulClaim",
    "SoulCore",
    "content_hash",
    "load_soul",
    "parse_spec",
    "render_soul_md",
    "seal_spec",
    "validate_spec",
    "DecayConfig",
    "EvictionCandidate",
    "MemoryNode",
    "MemoryTier",
    "effective_half_life_days",
    "eviction_candidates",
    "merge_node",
    "normalised_strength",
    "strength_at",
    "ContractViolation",
    "GovernanceError",
    "SoulCoreError",
    "UnauthorizedOverride",
    "Decision",
    "IdentityConsistencyEngine",
    "SoulVerdict",
    "require_human_override",
    "EvaluationReport",
    "IdentityEvaluator",
    "MemoryHygieneReport",
    "DimensionScore",
    "Probe",
    "TargetAgent",
    "CallableAgent",
    "ScriptedAgent",
    "AnchoredMemoryAgent",
    "build_probe_suite",
    "memory_hygiene",
    "HeuristicScorer",
    "LLMScorer",
    "ScoreVector",
    "ScoringProfile",
    "composite_score",
    "from_llm_1_10",
    "parse_score_response",
    "ConsolidationReport",
    "Edge",
    "Event",
    "EventState",
    "MemoryHit",
    "MemoryLedger",
    "MemoryPolicy",
    "MemoryReport",
    "ObserveOutcome",
    "Person",
    "PersonState",
    "RecallResult",
    "EDGE_INTERACTED",
    "EDGE_INVOLVED",
    "EDGE_MENTIONED",
    "EVENT_PREFIX",
    "PERSON_PREFIX",
    "name_similarity",
    "text_similarity",
    "JsonlPersistence",
    "MemoryStore",
    "NullPersistence",
    "ObservationResult",
]
